/**
 * Essential sentences from Essential.csv
 * Auto-generated from data_preparation/data/output/sentences_by_difficulty/Essential.csv
 * Last updated: 2025-12-30
 * 
 * To regenerate from CSV, run: node scripts/updateEssentialSentences.js
 */

export const essentialSentences = [
  "Good afternoon",
  "Hello",
  "Goodbye",
  "Good morning",
  "Good evening",
  "You're welcome",
  "Good night",
  "Yes",
  "Nice to meet you.",
  "It doesn't matter",
  "I'm fine, thank you.",
  "Sorry",
  "No",
  "Please",
  "Maybe",
  "How are you?",
  "What time is it?",
  "Can you explain it?",
  "Can you help me?",
  "I don't think so",
  "I know",
  "I understand",
  "Thank you",
  "Repeat, please",
  "No problem",
  "See you later",
  "Excuse me",
  "I don't know",
  "What does this mean?",
  "Do you understand?",
  "When?",
  "Please help me.",
  "I don't understand",
  "I think so",
  "Can you show me?",
  "I need help.",
  "I am a teacher",
  "What is your name?",
  "My name is Paul",
  "Do you speak English?",
  "Can you write it down?",
  "I want a coffee.",
  "I am from Germany",
  "I speak only a little English.",
  "I am a tourist.",
  "Help!",
  "Please speak slowly",
  "I am 24 years old.",
  "I like it.",
  "I don't like it.",
  "Good evening.",
  "What do you do?",
  "Go faster",
  "It's good.",
  "Where are you from?",
  "Wait",
  "It's okay.",
  "How old are you?",
  "One less.",
  "I need help now.",
  "I am tired.",
  "One more.",
  "It's bad.",
  "Where is the toilet?",
  "Slow down",
];
