// AUTO-GENERATED by atmn pull
// DO NOT EDIT MANUALLY

declare module '@useautumn/sdk' {
  // Features
  export const chat_messages: Feature;
  export const courses: Feature;
  export const reviews: Feature;
  export const sentences: Feature;
  export const custom_sentences: Feature;
  export const multiple_languages: Feature;
  export const transcriptions: Feature;
  export const custom_phrases: Feature;

  // Plans
  export const free: Plan;
  export const basic: Plan;
  export const pro: Plan;

  // Base types
  export type Feature = import('./autumn.config').Feature;
  export type Plan = import('./autumn.config').Plan;
}
