// AUTO-GENERATED by atmn pull
// DO NOT EDIT MANUALLY

import type {} from '@useautumn/sdk';

declare module '@useautumn/sdk' {
  // Features
  export const sentences: Feature;
  export const audioRegenerations: Feature;
  export const cardEdits: Feature;
  export const transcriptions: Feature;
  export const courses: Feature;
  export const chatMessages: Feature;
  export const customSentences: Feature;
  export const multipleLanguages: Feature;
  export const translationAutoFill: Feature;
  export const translationFlags: Feature;
  export const credits: Feature;

  // Plans
  export const free: Plan;
  export const pro: Plan;
  export const basic: Plan;

  // Base types
  export type Feature = import('./autumn.config').Feature;
  export type Plan = import('./autumn.config').Plan;
}
