import { describe, it, expect } from 'vitest';
import { resetStaleCantoneseRomanizationPatch } from '../../migrations';
import { ROMANIZATION_SOURCES } from '../../lib/localRomanization';

const CLEARED = { romanizedText: undefined, romanizationSource: undefined };

describe('resetStaleCantoneseRomanizationPatch (migrateOne logic)', () => {
  it('clears rows tagged with the retired cantonese-romanisation source', () => {
    expect(
      resetStaleCantoneseRomanizationPatch({
        language: 'yue_traditional',
        romanizedText: 'ng4 oi2 nei5',
        romanizationSource: 'cantonese-romanisation-v1',
      }),
    ).toEqual(CLEARED);
  });

  it('clears untagged Cantonese rows written before the source field existed', () => {
    // The retired library shipped one commit before romanizationSource was
    // added to the schema, so its earliest output carries no tag at all.
    expect(
      resetStaleCantoneseRomanizationPatch({
        language: 'yue_traditional',
        romanizedText: 'ng4 oi2 nei5',
        romanizationSource: undefined,
      }),
    ).toEqual(CLEARED);
  });

  it('clears the empty-string "tried, failed" sentinel on Cantonese rows', () => {
    expect(
      resetStaleCantoneseRomanizationPatch({
        language: 'yue',
        romanizedText: '',
        romanizationSource: undefined,
      }),
    ).toEqual(CLEARED);
  });

  it('leaves rows already regenerated by the current to-jyutping source untouched', () => {
    // The lazy pipeline may have rewritten rows between deploy and the
    // migration run — those are correct and must not be cleared.
    expect(
      resetStaleCantoneseRomanizationPatch({
        language: 'yue_traditional',
        romanizedText: 'm4 oi3 nei5',
        romanizationSource: ROMANIZATION_SOURCES.toJyutping,
      }),
    ).toBeUndefined();
  });

  it('leaves never-attempted rows untouched — the lazy pipeline owns them', () => {
    expect(
      resetStaleCantoneseRomanizationPatch({
        language: 'yue',
        romanizedText: undefined,
        romanizationSource: undefined,
      }),
    ).toBeUndefined();
  });

  it('leaves non-Cantonese rows untouched regardless of tag state', () => {
    expect(
      resetStaleCantoneseRomanizationPatch({
        language: 'zh',
        romanizedText: 'nǐ hǎo',
        romanizationSource: undefined,
      }),
    ).toBeUndefined();
    expect(
      resetStaleCantoneseRomanizationPatch({
        language: 'ko',
        romanizedText: 'hangungmal',
        romanizationSource: ROMANIZATION_SOURCES.esHangul,
      }),
    ).toBeUndefined();
  });

  it('is idempotent — a cleared row is not patched again on re-run', () => {
    expect(
      resetStaleCantoneseRomanizationPatch({
        language: 'yue_traditional',
        romanizedText: undefined,
        romanizationSource: undefined,
      }),
    ).toBeUndefined();
  });
});
