// GENERATED by scripts/classify-speaker-gender.mts (`pnpm classify:speaker -- --emit`)
// from data_preparation/ogte-dataset/data/output/speaker_gender.csv. Do not edit.
//
// The curriculum sentences whose English fixes their speaker: OGTE `id`
// (`texts.externalId`) to verdict. The neutral verdicts (20546
// of 20574) are not listed: the resolver treats an unstamped
// `speakerGender` as the coin flip anyway (lib/sentenceMetadataSource.ts).
// Written onto every deployment's texts by the `applySpeakerGenderVerdicts`
// migration in convex/migrations.ts.

/** The model the listed verdicts came from. */
export const SPEAKER_GENDER_VERDICTS_MODEL =
  'google/gemini-2.5-flash-lite:floor';

export const SPEAKER_GENDER_VERDICTS: Readonly<
  Record<string, 'male' | 'female'>
> = {
  '1337': 'male',
  '1977902': 'male',
  '2107335': 'male',
  '2240800': 'male',
  '2248329': 'male',
  '2293268': 'male',
  '247784': 'male',
  '253676': 'male',
  '2544755': 'male',
  '256155': 'male',
  '259412': 'male',
  '259527': 'male',
  '2713780': 'male',
  '2953818': 'male',
  '3250915': 'male',
  '3737009': 'male',
  '3825823': 'male',
  '386704': 'male',
  '388869': 'male',
  '4398772': 'male',
  '453328': 'male',
  '4999894': 'male',
  '5171726': 'male',
  '5512944': 'male',
  '5858279': 'male',
  '5859230': 'male',
  '6033360': 'male',
  '953581': 'male',
};
