/**
 * Wrapper around `cap sync` for the three shell environments
 * (pnpm cap:local | cap:dev | cap:store). Besides setting CAP_SERVER for
 * capacitor.config.ts, it generates native/shell/app-url.js so the offline
 * error page retries against the SAME environment instead of a hardcoded
 * production URL.
 */

import { writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

const MODES = {
  local: 'http://localhost:3000/app',
  dev: 'https://dev.flexling.com/app',
  store: 'https://flexling.com/app',
};

const mode = process.argv[2];
if (!(mode in MODES)) {
  console.error(
    `Usage: node scripts/cap-sync.mjs <${Object.keys(MODES).join('|')}>`,
  );
  process.exit(1);
}

writeFileSync(
  'native/shell/app-url.js',
  `// Generated by scripts/cap-sync.mjs (${mode}) — do not edit, not committed.\n` +
    `window.FLEXLING_APP_URL = ${JSON.stringify(MODES[mode])};\n`,
);

const result = spawnSync('npx', ['cap', 'sync'], {
  stdio: 'inherit',
  env: { ...process.env, CAP_SERVER: mode },
});
process.exit(result.status ?? 1);
