/**
 * Landing-page audio playback helpers.
 *
 * Audio files are pre-generated by `scripts/generate-landing-audio.mts` and
 * served as static assets from `/public/audio/landing/`. The manifest maps
 * (lang, raw text) → public URL so components can look up audio with the
 * same strings they're already rendering.
 */
import manifest from './audio-manifest.json';

const TYPED_MANIFEST = manifest as Record<string, Record<string, string>>;

export function getLandingAudioUrl(text: string, lang: string): string | null {
  return TYPED_MANIFEST[lang]?.[text] ?? null;
}

// Single shared element so a manual click cancels in-flight autoplay (and
// vice versa). Created lazily on first play to avoid SSR access to `Audio`.
let current: HTMLAudioElement | null = null;

export function playLandingAudio(url: string): void {
  if (typeof window === 'undefined') return;
  if (current) {
    current.pause();
    current.src = '';
  }
  current = new Audio(url);
  current.play().catch(() => {
    // Browsers reject play() with NotAllowedError when there's no prior user
    // gesture. The landing demos only autoplay after a tab/replay click, so
    // this should rarely trigger; swallow it silently when it does.
  });
}

export function stopLandingAudio(): void {
  if (current) {
    current.pause();
    current.src = '';
    current = null;
  }
}
